### ISSUE TITLE
Breaking change published with non-breaking version bump for match_token which breaks anyone using html5ever 0.31

### ISSUE THREAD

**Issue by Quentin01** [servo/html5ever#623]
`match_token` was bumped to `0.1.1` in #621 and contains a breaking change coming from #593, it should have been a bump to `0.2.0` as `0.1.0` to `0.1.1` isn't considered a breaking change.

The consequence of that, is anyone that is using `html5ever` 0.31 will now attempt to build it against `match_token` 0.1.1 resulting in a compilation error. Publishing `html5ever` 0.32 won't solve the issue as Cargo won't use the version 0.32 when the requirements is `^0.31`. Therefore, the only solution is to yank the version 0.1.1 of `match_token` and re-publish it with the version 0.2.0.

Since `html5ever` is widely used, this issue will impact a large number of users, such as our current inability to install `mdbook`, which depends on `ammonia`, which in turn depends on `html5ever` 0.31.

Thanks

**Comment by epage** [comment]
Cargo's CI is failing because of this is causing [linkchecker](https://github.com/rust-lang/rust/tree/master/src/tools/linkchecker) to fail to build which uses `html5ever@0.29.0`.  The way `linkchecker.sh` works is it downloads only the `Cargo.toml` and `main.rs` so we don't have access to the lockfile.

**Comment by nicoburns** [comment]
@servo/cargo-publish Can someone yank version `0.1.1` of the `match_token` crates as a matter of urgency? It seems we're breaking the CI of at least Cargo and MDBook.

**Comment by sagudev** [comment]
> [@servo/cargo-publish](https://github.com/orgs/servo/teams/cargo-publish) Can someone yank version `0.1.1` of the `match_token` crates as a matter of urgency? It seems we're breaking the CI of at least Cargo and MDBook.

Done.

**Comment by sagudev** [comment]
We will still need to republish `match_token` as 0.2.0 and publish patch releases for other crates with new version of `match_token`.

**Comment by atouchet** [comment]
The html5ever 0.32 release depends on match_token 0.1.1. Should that be yanked too?

**Comment by nicoburns** [comment]
It makes less difference for html5ever 0.32 as it is not possible to install it either way. Probably:
-  A `0.32.1` release that depends on match_token `0.2.0` should be made
- `0.32.0` should be yanked

But this is less immediately urgent and the ordering is less important as it won't break anyone's build, they just won't be able to upgrade.

**Comment by nicoburns** [comment]
Somebody should probably check my work, but I have attempted to go through and fixup all of the crates in the repository in https://github.com/servo/html5ever/pull/625
